In [3]:
import pandas as pd

In [7]:
image_names = ["9ArrD 316 Git1GFPA_006",
              "9ArrD Aly1 Git1GFPA_005",
              "9ArrD Aly2 Git1GFPA_004",
              "9ArrD Csr2 Git1GFPA_004",
              "9ArrD Ecm21 Git1GFPA_006",
              "9ArrD Ldb19 Git1GFPA_005",
              "9ArrD Rod1 Git1GFPA_011",
              ]
base_path =  "C:/Users/sarah/Desktop/CellQuantAndLoc/O-Donnell-Lab/Git1 Automated Quant - First Pass/"

csv_categories = ["PM_vac_ratio", "cell_mpi", "vac_mpi"]
image_dfs = {}

In [8]:
for image_name in image_names:
    image_dfs[image_name] = pd.read_csv(base_path + image_name + "_results.csv")

In [71]:
def get_max(image_names):
    max_cells = -1
    max_name = ""
    for image_name in image_names:
        s = image_dfs[image_name]["CellID"].size
        if(s > max_cells):
            max_cells = s
            max_name = image_name
           # print(max_cells, max_name)
    return(max_name)

In [ ]:
dfs = []
for category in csv_categories:
    df =

In [80]:
image_dfs[get_max(image_names)]["CellID"].values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int64)

In [82]:
df = pd.DataFrame(columns= image_dfs[get_max(image_names)]["CellID"].values)
df["Image"] = image_names
cols = df.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df[cols]

df

,Image,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,9ArrD 316 Git1GFPA_006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9ArrD Aly1 Git1GFPA_005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9ArrD Aly2 Git1GFPA_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9ArrD Csr2 Git1GFPA_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9ArrD Ecm21 Git1GFPA_006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,9ArrD Ldb19 Git1GFPA_005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,9ArrD Rod1 Git1GFPA_011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
s = "9ArrD Aly1 Git1GFPA_005"
category = "cell_mpi"
image_dfs[s][category]

0     0.157364
1     0.119518
2     0.056376
3     0.163657
4     0.157359
5     0.066615
6     0.218540
7     0.151602
8     0.252758
9     0.270259
10    0.040550
11    0.069116
12    0.309286
13    0.201303
14    0.041141
15    0.311561
16    0.266677
17    0.073605
18    0.075341
19    0.064711
20    0.295116
21    0.224347
22    0.101432
23    0.064550
24    0.172909
25    0.096726
26    0.207119
27    0.222596
28    0.159770
29    0.233406
30    0.131522
31    0.047779
32    0.201894
33    0.237958
34    0.061993
35    0.067304
36    0.213630
37    0.225742
38    0.174195
39    0.083037
40    0.178431
41    0.265798
42    0.194865
43    0.144140
44    0.070083
45    0.164923
46    0.388662
47    0.246421
Name: cell_mpi, dtype: float64

In [88]:
image_dfs[s][category].values

array([0.15736448, 0.11951824, 0.056376  , 0.16365661, 0.15735899,
       0.06661456, 0.21854015, 0.15160241, 0.25275829, 0.27025942,
       0.0405501 , 0.06911635, 0.3092859 , 0.20130256, 0.04114103,
       0.31156086, 0.26667677, 0.07360465, 0.0753412 , 0.06471095,
       0.29511623, 0.22434721, 0.10143165, 0.06454986, 0.17290945,
       0.09672631, 0.2071187 , 0.22259629, 0.15977006, 0.233406  ,
       0.131522  , 0.04777899, 0.20189426, 0.23795756, 0.06199276,
       0.06730439, 0.21362996, 0.22574155, 0.17419544, 0.08303726,
       0.17843143, 0.26579784, 0.19486453, 0.1441403 , 0.07008266,
       0.1649229 , 0.38866222, 0.24642146])